const KEY="habitly-bright-v1",icons=["📖","🌅","🕌","🏃","💧","🧘","✍️","💼","🏠","❤️","🎯","🥗","🧠","☀️","🌙"];
const defaults={habits:[{id:1,name:"Подъём 7:00",icon:"🌅",time:"07:00"},{id:2,name:"Фаджр",icon:"🕌",time:"05:20"},{id:3,name:"Утренние зикры",icon:"📖",time:"08:00"},{id:4,name:"Читать 10 страниц",icon:"📖",time:"10:00"},{id:5,name:"Тренировка",icon:"🏃",time:"18:00"},{id:6,name:"Дневник",icon:"✍️",time:"21:00"}],done:{}};
let data=load(),editing=null,view=new Date(),selected=iso(new Date()),chosenIcon="📖",toastTimer;
function load(){try{return JSON.parse(localStorage.getItem(KEY))||structuredClone(defaults)}catch{return structuredClone(defaults)}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function iso(d){d=new Date(d);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function parse(k){return new Date(k+"T12:00:00")}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function fmt(d,o={day:"numeric",month:"long",year:"numeric"}){return d.toLocaleDateString("ru-RU",o)}
function done(k,id){return(data.done[k]||[]).includes(id)}
function pct(k){let n=data.habits.length;if(!n)return 0;let d=(data.done[k]||[]).filter(id=>data.habits.some(h=>h.id===id)).length;return Math.round(d/n*100)}
function avg(){let a=[],now=new Date();for(let i=0;i<30;i++){let d=new Date();d.setDate(now.getDate()-i);if(data.habits.length)a.push(pct(iso(d)))}return a.length?Math.round(a.reduce((x,y)=>x+y,0)/a.length):0}
function streak(){let s=0,d=new Date();while(pct(iso(d))===100&&data.habits.length){s++;d.setDate(d.getDate()-1)}return s}
function toast(s){let e=document.getElementById("toast");e.textContent=s;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),1500)}
function toggle(id){let k=iso(new Date());data.done[k]??=[];let a=data.done[k],i=a.indexOf(id);i<0?a.push(id):a.splice(i,1);save();render();toast(i<0?"Готово ✨":"Отменено")}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.toggle("active",x.id===id));document.querySelectorAll(".nav button").forEach(x=>x.classList.toggle("active",x.dataset.screen===id));render()}
function renderStrip(){let e=document.getElementById("monthStrip"),d=new Date();d.setDate(d.getDate()-3);let h="";for(let i=0;i<7;i++){let x=new Date(d);x.setDate(d.getDate()+i),k=iso(x);h+=`<button class="date-pill ${k===selected?"selected":""}" onclick="selectDate('${k}')"><span>${x.toLocaleDateString("ru-RU",{weekday:"short"}).replace(".","")}</span><b>${x.getDate()}</b></button>`}e.innerHTML=h}
function selectDate(k){selected=k;renderStrip();renderDayInfo()}
function renderHome(){let k=iso(new Date()),p=pct(k),d=(data.done[k]||[]).length;document.getElementById("percent").textContent=p+"%";document.getElementById("ringText").textContent=p+"%";document.getElementById("ring").style.setProperty("--p",p+"%");document.getElementById("countText").textContent=`${d} из ${data.habits.length} выполнено`;document.getElementById("progressText").textContent=p===100?"Все привычки выполнены 🎉":p?`Осталось ${data.habits.length-d}`:"Начните с первой привычки";let e=document.getElementById("habits");e.innerHTML=data.habits.length?data.habits.map(h=>`<div class="habit ${done(k,h.id)?"done":""}"><button class="check" onclick="toggle(${h.id})">${done(k,h.id)?"✓":""}</button><div class="emoji">${h.icon}</div><div class="name">${esc(h.name)}<div class="time">${h.time||"В любое время"}</div></div><button class="more" onclick="editHabit(${h.id})">⋯</button></div>`).join(""):`<div class="empty">Создай первую привычку 🌱</div>`}
function renderCalendar(){let y=view.getFullYear(),m=view.getMonth(),first=new Date(y,m,1),off=(first.getDay()+6)%7,n=new Date(y,m+1,0).getDate(),h=["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x=>`<div class="dow">${x}</div>`).join("");for(let i=0;i<off;i++)h+="<div></div>";for(let i=1;i<=n;i++){let k=iso(new Date(y,m,i)),p=pct(k),c=p>=90?"good":p>=50?"mid":p?"bad":"";h+=`<button class="cal-day ${c} ${k===iso(new Date())?"today":""}" onclick="selectDate('${k}')">${i}<span class="dot"></span></button>`}document.getElementById("calendar").innerHTML=h;document.getElementById("monthName").textContent=view.toLocaleDateString("ru-RU",{month:"long",year:"numeric"});renderDayInfo()}
function renderDayInfo(){let k=selected,p=pct(k),d=parse(k);document.getElementById("dayInfo").innerHTML=`<h3>${fmt(d)} · ${p}%</h3><div class="line"><i style="width:${p}%"></i></div><p style="color:#999;font-size:12px">${(data.done[k]||[]).length} из ${data.habits.length} выполнено</p>${data.habits.map(h=>`<div class="detail"><div class="mini ${done(k,h.id)?"on":""}">${done(k,h.id)?"✓":""}</div><span>${h.icon} ${esc(h.name)}</span></div>`).join("")}`}
function renderStats(){let av=avg();document.getElementById("avg").textContent=av+"%";document.getElementById("avgBar").style.width=av+"%";let c=document.getElementById("weekChart"),h="";for(let i=6;i>=0;i--){let d=new Date();d.setDate(d.getDate()-i);let p=pct(iso(d));h+=`<div class="col" style="height:${Math.max(5,p)}%"><small>${d.getDate()}</small></div>`}c.innerHTML=h;document.getElementById("habitStats").innerHTML=data.habits.map(h=>{let a=0;for(let i=0;i<30;i++){let d=new Date();d.setDate(d.getDate()-i);if(done(iso(d),h.id))a++}let p=Math.round(a/30*100);return `<div class="habit-stat"><span>${h.icon} ${esc(h.name)}</span><strong>${p}%</strong><div class="line"><i style="width:${p}%"></i></div></div>`}).join("")}
function render(){renderStrip();renderHome();renderCalendar();renderStats()}
function openNew(){editing=null;chosenIcon="📖";document.getElementById("modalTitle").textContent="Что хочешь делать каждый день?";document.getElementById("name").value="";document.getElementById("time").value="08:00";document.getElementById("delete").classList.add("hidden");drawIcons();document.getElementById("modal").classList.add("show")}
function editHabit(id){let h=data.habits.find(x=>x.id===id);if(!h)return;editing=id;chosenIcon=h.icon;document.getElementById("modalTitle").textContent="Изменить привычку";document.getElementById("name").value=h.name;document.getElementById("time").value=h.time||"08:00";document.getElementById("delete").classList.remove("hidden");drawIcons();document.getElementById("modal").classList.add("show")}
function drawIcons(){document.getElementById("icons").innerHTML=icons.map(x=>`<button class="icon ${x===chosenIcon?"sel":""}" onclick="pickIcon('${x}')">${x}</button>`).join("")}
function pickIcon(x){chosenIcon=x;drawIcons()}
function close(){document.getElementById("modal").classList.remove("show")}
function saveHabit(){let n=document.getElementById("name").value.trim();if(!n){toast("Напиши название привычки");return}if(editing){let h=data.habits.find(x=>x.id===editing);h.name=n;h.icon=chosenIcon;h.time=document.getElementById("time").value}else data.habits.push({id:Date.now(),name:n,icon:chosenIcon,time:document.getElementById("time").value});save();close();render();toast("Привычка сохранена ✨")}
function deleteHabit(){if(!editing)return;if(!confirm("Удалить привычку?"))return;data.habits=data.habits.filter(h=>h.id!==editing);Object.keys(data.done).forEach(k=>data.done[k]=data.done[k].filter(id=>id!==editing));save();close();render();toast("Удалено")}
document.querySelectorAll(".nav button").forEach(b=>b.onclick=()=>show(b.dataset.screen));document.getElementById("addBtn").onclick=openNew;document.getElementById("addLarge").onclick=openNew;document.getElementById("close").onclick=close;document.getElementById("cancel").onclick=close;document.getElementById("save").onclick=saveHabit;document.getElementById("delete").onclick=deleteHabit;document.getElementById("prev").onclick=()=>{view.setMonth(view.getMonth()-1);render()};document.getElementById("next").onclick=()=>{view.setMonth(view.getMonth()+1);render()};document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")close()};render();
